### PR TITLE
draft index.rst for CORE-V Docs

### PR DESCRIPTION
**Pull request by rickoco**
building on work done previously by @davideschiavone , this PR is the start of creating an Index landing page for all CORE-V related documentation.  A readthedocs rendering can be seen here https://openhw-group-core-v-docs-dev.readthedocs-hosted.com/en/latest/

### CODE REVIEW

**Review by MikeOpenHWGroup — CHANGES_REQUESTED** [review]
I'm liking this idea! Recommend we put this into it's own top-level directory (RTD defaults to "docs", but we can call it anything we want.)  We could also move the `idcodes.md` into the same directory and make it a section of the RTD rendering.

**Comment by rickoco** [comment]
@MikeOpenHWGroup - I'm not sure what you're asking for.  You want the index for core-v-docs inside a subdirectory called /docs (core-v-docs/docs/)?  Seems like unnecessary nesting IMHO.  I agree about including the idcodes.md which is a change we can make after the PR is merged as there's a bunch of further changes / additions to make...

**Comment by MikeOpenHWGroup** [comment]
Agree that `core-v-docs/docs` is a bit odd, so a better name for the sub-dir would be good (`LandingPageIndex`, maybe?).  I do not see it as unnecessary nesting.  We've already got three files: `cores.rst`, `index.rst` and `idcodes.md` (previously contributed by Florian).  Its a good bet that we'll want to add more and over a short period of time that will lead to a lot of files clustering the top-level.

**Comment by rickoco** [comment]
ok - fair enough.  So, let's go with /DocsIndex then.  Is it best that I cancel this PR and re-issue a new PR with everything in /DocsIndex?

**Comment by MikeOpenHWGroup** [comment]
I am "pretty sure" you can make the changes in your current working copy and then commit/push onto the rickoco:master branch of your fork.  The PR is updated accordingly.

**Comment by rickoco** [comment]
So turns out 'index.rst' needs to be in the repo root or '\docs\' directory.  I've moved everything to '\docs\' and will let you know when to merge after some rendering testing with rtd.  *don't merge yet*

**Comment by rickoco** [comment]
Fixed up file locations, some formatting and added images.  More formatting and content to be added, but ready to merge now... https://openhw-group-core-v-docs-dev.readthedocs-hosted.com/en/latest/index.html

**Review by MikeOpenHWGroup — APPROVED** [review]

**Pull request merged**
