### PR TITLE
Documentation updates of the HPM for openhwgroup/cv32e40p#432

### PR DESCRIPTION
**Pull request by jm4rtin**
Signed-off-by: John Eric Martin <John.Martin@emmicro-us.com>

### CODE REVIEW

**Review by Silabs-ArjanB — COMMENTED** [review]
Hi John, 

Thanks for updating the docs. What you added looks good. Could you please also add the following:

- Add Zicount (which according to https://github.com/riscv/riscv-isa-manual/issues/548 seems to become the new name for this extension) in table 1 of https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/intro.html.
- Add the equivalent of https://ibex-core.readthedocs.io/en/latest/cs_registers.html#time-registers-time-h as a note in our https://core-v-docs-verif-strat.readthedocs.io/projects/cv32e40p_um/en/latest/perf_counters.html chapter (not in the CSR chapter as far as I am concerned).

**Review by Silabs-ArjanB — APPROVED** [review]

**Comment by jm4rtin** [comment]
I'm not actually sure on the version of that extension. The Ibex documentation mentions a `mtimeh` register which doesn't exist. The spec states `mtime` is a 64-bit memory-mapped register on all platforms.

**Comment by Silabs-ArjanB** [comment]
Hi @jm4rtin Do you know why above error about 'legal agreements' occurs?

**Comment by Silabs-ArjanB** [comment]
> 
> 
> I'm not actually sure on the version of that extension. The Ibex documentation mentions a `mtimeh` register which doesn't exist. The spec states `mtime` is a 64-bit memory-mapped register on all platforms.

I think it is okay like this for now. Once the RISC-V community actually gives it a name, then it will probably receive a version as well and we can update if needed.

**Pull request merged**
