### PR TITLE
Adding HWloop constraints in documentation

### PR DESCRIPTION
**Pull request by davideschiavone**
These constraints were already part of the RTL but not in the documentation.

Pinging @jeremybennett for compiler side.

It aims to solve #265

### CODE REVIEW

**Review by jm4rtin — APPROVED** [review]

**Comment by jeremybennett** [comment]
Hold on. This is a load of new constraints on the compiler using hardware loop. Let's review with the software tools projects before committing them.  Anything that changes the ISA should have one of the software team as reviewer.

**Comment by jeremybennett** [comment]
I'm not saying we shouldn't have these changes, and in this case, I don't think you have broken any of the committed tool chain work. But potentially ISA changes cause major problems for approved software projects.  In this case we don't have generic HW loop using - only for block copy. But extensive constraints like this are going to make use of HW loop by the compiler for anything else almost impossible.

**Comment by davideschiavone** [comment]
Completly agree @jeremybennett ! Every ISA change must be reviewed by at least one SW and one HW person.
I mentioned you on another issue so I was waiting for you input anyway, but I will add you as review here as well

**Comment by davideschiavone** [comment]
> 
> 
> I'm not saying we shouldn't have these changes, and in this case, I don't think you have broken any of the committed tool chain work. But potentially ISA changes cause major problems for approved software projects. In this case we don't have generic HW loop using - only for block copy. But extensive constraints like this are going to make use of HW loop by the compiler for anything else almost impossible.

Well, the HWLoop can be used not only for copies but especially for computational dense kernels.

for example:

start:
lw
lw
lw
lw
mac
end: mac

here we prohibit if else computation (as we forbit branches) . Pinging @eflamand to get his input as well

**Comment by jeremybennett** [comment]
@davideschiavone Thanks. The best reviewers to add are @jessicamills (GNU Tools Project lead) and André Sintzoff (LLVM Tools Project lead). You might find it useful to add @flip1995 since he is actively developing LLVM for CV32E40P.

**Comment by jeremybennett** [comment]
> Well, the HWLoop can be used not only for copies but especially for computational dense kernels.
> 
> for example:
> 
> start:
> lw
> lw
> lw
> lw
> mac
> end: mac
> 
> here we prohibit if else computation (as we forbit branches) . Pinging @eflamand to get his input as well

@davideschiavone Yes, I know this is where we would like HW loop to be used. The challenge is getting the compiler to recognize this and generate a hardware loop with multiple constraints on the instructions which can appear within the loop. We almost have the constraint of a single basic block as loop body with the ban on conditional branches, except that we can nest hardware loops.

I'm not saying not to do it, just that we should consider the impact on the compiler tool chains.

**Comment by davideschiavone** [comment]
Hi @jeremybennett , thanks for your comments. Design's choices and Decisions are driven by members. So we should all discuss what to do with the HWLoop. 

I cannot add @jessicamills and @flip1995. I guess they need to enable something. Can you confirm that?

**Comment by flip1995** [comment]
AFAIK, GitHub only lets you add members / collaborators of the org / repo as reviewers.

**Comment by davideschiavone** [comment]
I invited them. They should now accept it - then I should be able to add them as reviewers

**Comment by davideschiavone** [comment]
As decided during the meeting to RELOCATE the XPULP instruction and change the HWLoop ISA,

we decided accept these new constraints

**Pull request merged**
