### PR TITLE
Updated Xpulp Verification Plans

### PR DESCRIPTION
**Pull request by DavidM-EMUS**
A couple of the updated verification plans in this pull request depend on resolution of issues filed with the documentation in order for them to be valid:

CV32E40P_xpulp-bitmanipulation:
  -Cells D8-D11 require resolution of documentation issue https://github.com/openhwgroup/core-v-docs/issues/135

CV32E40P_xpulp-packed-simd:
  -Cells C94-C99 require resolution of documentation issue https://github.com/openhwgroup/core-v-docs/issues/139

### CODE REVIEW

**Comment by DavidM-EMUS** [comment]
@MikeOpenHWGroup I just added the exception verification plan to this pull request. I'll update the title to reflect the change

**Comment by DavidM-EMUS** [comment]
@MikeOpenHWGroup I just reverted back to the commit that only adds the Xpulp Vplans. Please keep in mind that issues #135  and #139 as listed in my initial comment are still unaddressed at this time

**Review by MikeOpenHWGroup — APPROVED** [review]
Thanks @DavidM-EMUS!

**Comment by MikeOpenHWGroup** [comment]
>  Please keep in mind that issues #135  and #139 as listed in my initial comment are still unaddressed at this time

Understood.  Given that these issues are related to Xpulp tests, the design team will treat these with a lower priority.  I'll raise this issue at the next cv32e40p status review.

**Pull request merged**
