### PR TITLE
Issue summary

### PR DESCRIPTION
**Pull request by MikeOpenHWGroup**
As per @davideschiavone request, I've added the issue summary to the verification section of the User Manual's introduction.

### CODE REVIEW

**Comment by davideschiavone** [comment]
Hi @MikeOpenHWGroup , it looks good to me but, should we also include which kind of bugs have been found? like which of the 40 RTLs bugs? do we have such info easily accessible? it's probably in closed issues.
Also ,before merging I would like to know whether we can MERGE , as we wanted to hold until RTL Freeze . So for this I ask @Silabs-ArjanB to have a look at the PR and to express an opinion whether this report should be included in the RTL Freeze (by thus moving the documentation tag) or this PR should hold until that day.

**Comment by MikeOpenHWGroup** [comment]
> should we also include which kind of bugs have been found? like which of the 40 RTLs bugs? do we have such info easily accessible?

This information is available in the CV32E40P v1.0.0 Report.  I'll be adding a spreadsheet with summary information on each issue to that location and there is a link to it as part of this pull-request.

> Also ,before merging I would like to know whether we can MERGE , as we wanted to hold until RTL Freeze . So for this I ask @Silabs-ArjanB to have a look at the PR and to express an opinion whether this report should be included in the RTL Freeze (by thus moving the documentation tag) or this PR should hold until that day.

As you see fit.

**Comment by Silabs-ArjanB** [comment]
> 
> 
> Hi @MikeOpenHWGroup , it looks good to me but, should we also include which kind of bugs have been found? like which of the 40 RTLs bugs? do we have such info easily accessible? it's probably in closed issues.
> Also ,before merging I would like to know whether we can MERGE , as we wanted to hold until RTL Freeze . So for this I ask @Silabs-ArjanB to have a look at the PR and to express an opinion whether this report should be included in the RTL Freeze (by thus moving the documentation tag) or this PR should hold until that day.

I am fine either way. Personally I think we should not refer to that press release as we officially still do not have achieved RTL freeze, so that release is a bit misleading (although of course the RTL has not changed). Also, I cannot find a list of those 40 RTL bugs anywhere. If you decide to move the freeze tag for the documentation, then you should either solve or mention https://github.com/openhwgroup/core-v-docs/issues/327 first.

**Comment by MikeOpenHWGroup** [comment]
> I think we should not refer to that press release as we officially still do not have achieved RTL freeze, 

I was just as surprised as you about that.

> I cannot find a list of those 40 RTL bugs anywhere

They will be added to the program section of core-v-docs.  A separate PR will be issued for that.  I guess there is nothing stopping me from doing that now, so that will be in before the of the day.

> If you decide to move the freeze tag for the documentation, then you should either solve or mention #327 first.

Agreed.

**Comment by davideschiavone** [comment]
> #327 first.

Let me solve #327 first

**Comment by davideschiavone** [comment]
PR #331 solves #327

**Comment by davideschiavone** [comment]
#331  has been merged and #327 closed. So it's good to me

**Comment by MikeOpenHWGroup** [comment]
@Silabs-ArjanB, I have pushed in an update that removes the reference to the news release.

**Review by Silabs-ArjanB — APPROVED** [review]

**Pull request merged**
