### PR TITLE
Rtl freeze milestone

### PR DESCRIPTION
**Pull request by davideschiavone**

### CODE REVIEW

**Review by Silabs-ArjanB — CHANGES_REQUESTED** [review]
Hi Davide,

Maybe you can add a sentence about the most recent existing core-v-docs github issue in Documentation_openissues.md  as well (and then also do the same in the Design_openissues.md file (I know that the info for the RTL repos is now in the User Manual, but I think it is more logical to add it in these new files)

**Comment by davideschiavone** [comment]
Hi @Silabs-ArjanB , there are these sentence in the *_openissue.md files:

At the time of applying the cv32e40p_v1.0.0 tag, there were the following open issues.

What else would you like to see?

**Comment by Silabs-ArjanB** [comment]
We need to document the most recent reported github issue that exist (otherwise we do not know which issues were known at the time of RTL freeze)

**Comment by davideschiavone** [comment]
I do not understand sorry.
If we have Documentation_openissues.md (in this PR) and Design_openissues.md already merged in.

**Comment by Silabs-ArjanB** [comment]
In the case of core-v-docs I would like you to add to the Documentation_openissues.md document that https://github.com/openhwgroup/core-v-docs/issues/299 is the most recent github issue. (This one happens to be open, but the most recent one could have been closed as well; we simply need to know what issues were known (no matter if they are open or closed) at the time of RTL freeze). Same story for core-v-verif and cv32e40p repos.

**Review by Silabs-ArjanB — APPROVED** [review]

**Pull request merged**
