### PR TITLE
Add reference to FPGA optimized Perf. Counters

### PR DESCRIPTION
**Pull request by ganoam**
See PR openhwgroup/cv32e40p#437

Signed-off-by: ganoam <gnoam@live.com>

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @ganoam.  I do not see the changes in the RTL.  Is there a pull-request on https://github.com/openhwgroup/cv32e40p to update the RTL to match these updates to the spec?

**Comment by ganoam** [comment]
Hi @MikeOpenHWGroup. Yes, they are in PR openhwgroup/cv32e40p#437.

**Comment by MikeOpenHWGroup** [comment]
:+1:

**Comment by MikeOpenHWGroup** [comment]
This PR is stale and no longer relavent to this repo.  Note that the User Manual for the CV32E40P has been moved to https://github.com/openhwgroup/cv32e40p.

Closing.

**Pull request closed without merging**
